/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestModalRouteImport } from './routes/test-modal'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as GoRouteImport } from './routes/go'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as IndexRouteImport } from './routes/index'

const TestModalRoute = TestModalRouteImport.update({
  id: '/test-modal',
  path: '/test-modal',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GoRoute = GoRouteImport.update({
  id: '/go',
  path: '/go',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/go': typeof GoRoute
  '/settings': typeof SettingsRoute
  '/store': typeof StoreRoute
  '/test-modal': typeof TestModalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/go': typeof GoRoute
  '/settings': typeof SettingsRoute
  '/store': typeof StoreRoute
  '/test-modal': typeof TestModalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/go': typeof GoRoute
  '/settings': typeof SettingsRoute
  '/store': typeof StoreRoute
  '/test-modal': typeof TestModalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/get-started'
    | '/go'
    | '/settings'
    | '/store'
    | '/test-modal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/get-started' | '/go' | '/settings' | '/store' | '/test-modal'
  id:
    | '__root__'
    | '/'
    | '/get-started'
    | '/go'
    | '/settings'
    | '/store'
    | '/test-modal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GetStartedRoute: typeof GetStartedRoute
  GoRoute: typeof GoRoute
  SettingsRoute: typeof SettingsRoute
  StoreRoute: typeof StoreRoute
  TestModalRoute: typeof TestModalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-modal': {
      id: '/test-modal'
      path: '/test-modal'
      fullPath: '/test-modal'
      preLoaderRoute: typeof TestModalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go': {
      id: '/go'
      path: '/go'
      fullPath: '/go'
      preLoaderRoute: typeof GoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GetStartedRoute: GetStartedRoute,
  GoRoute: GoRoute,
  SettingsRoute: SettingsRoute,
  StoreRoute: StoreRoute,
  TestModalRoute: TestModalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
