/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as GoRouteImport } from './routes/go'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsMybangsRouteImport } from './routes/settings.mybangs'
import { Route as SettingsConfigsRouteImport } from './routes/settings.configs'
import { Route as SettingsAboutRouteImport } from './routes/settings.about'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GoRoute = GoRouteImport.update({
  id: '/go',
  path: '/go',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMybangsRoute = SettingsMybangsRouteImport.update({
  id: '/mybangs',
  path: '/mybangs',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConfigsRoute = SettingsConfigsRouteImport.update({
  id: '/configs',
  path: '/configs',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/go': typeof GoRoute
  '/settings': typeof SettingsRouteWithChildren
  '/store': typeof StoreRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/configs': typeof SettingsConfigsRoute
  '/settings/mybangs': typeof SettingsMybangsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/go': typeof GoRoute
  '/settings': typeof SettingsRouteWithChildren
  '/store': typeof StoreRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/configs': typeof SettingsConfigsRoute
  '/settings/mybangs': typeof SettingsMybangsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/go': typeof GoRoute
  '/settings': typeof SettingsRouteWithChildren
  '/store': typeof StoreRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/configs': typeof SettingsConfigsRoute
  '/settings/mybangs': typeof SettingsMybangsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/go'
    | '/settings'
    | '/store'
    | '/settings/about'
    | '/settings/configs'
    | '/settings/mybangs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/go'
    | '/settings'
    | '/store'
    | '/settings/about'
    | '/settings/configs'
    | '/settings/mybangs'
  id:
    | '__root__'
    | '/'
    | '/go'
    | '/settings'
    | '/store'
    | '/settings/about'
    | '/settings/configs'
    | '/settings/mybangs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GoRoute: typeof GoRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StoreRoute: typeof StoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go': {
      id: '/go'
      path: '/go'
      fullPath: '/go'
      preLoaderRoute: typeof GoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/mybangs': {
      id: '/settings/mybangs'
      path: '/mybangs'
      fullPath: '/settings/mybangs'
      preLoaderRoute: typeof SettingsMybangsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/configs': {
      id: '/settings/configs'
      path: '/configs'
      fullPath: '/settings/configs'
      preLoaderRoute: typeof SettingsConfigsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsConfigsRoute: typeof SettingsConfigsRoute
  SettingsMybangsRoute: typeof SettingsMybangsRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsConfigsRoute: SettingsConfigsRoute,
  SettingsMybangsRoute: SettingsMybangsRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GoRoute: GoRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StoreRoute: StoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
