/// <reference lib="webworker" />
import { precacheAndRoute } from "workbox-precaching";
import { getRedirectUrl } from "./lib/engine";

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by build process
precacheAndRoute(self.__WB_MANIFEST);

// Intercept /go requests for instant redirection
self.addEventListener("fetch", (event: FetchEvent) => {
	const url = new URL(event.request.url);

	if (url.pathname === "/go") {
		const query = url.searchParams.get("q");

		if (query) {
			event.respondWith(
				(async () => {
					try {
						const redirectUrl = await getRedirectUrl(query);
						return Response.redirect(redirectUrl, 302);
					} catch (error) {
						console.error("SW Redirect Error:", error);
						// Fallback to fetch if something goes wrong
						return fetch(event.request);
					}
				})(),
			);
		}
	}
});

// Skip waiting to activate the new SW immediately
self.addEventListener("install", () => {
	self.skipWaiting();
});
